apiVersion: apps/v1
kind: Deployment
metadata:
  name: wincpool
  labels:
    app: wincpool
spec:
  replicas: 1
  template:
    metadata:
      name: wincpool
      labels:
        app: wincpool
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: wincpool
        image: microsoft/mssql-server-windows-developer 
        env:
        - name: sa_password
          value: "W3!come0001"
        - name: ACCEPT_EULA 
          value: "Y"
        resources:
          limits:
            cpu: 1
            memory: 4G
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
            name: other 
            protocol: TCP
          - containerPort: 8080
            name: wiremock
            protocol: TCP
          - containerPort: 1433
            name: mssql
            protocol: TCP
      imagePullSecrets:
      - name: regcred
  selector:
    matchLabels:
      app: wincpool 